2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Tim de Boer\.config\wandb\settings
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_setup.py:_flush():76] Loading settings from wandb\settings
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'realsweep2-EEGNET-fullrun835Hz_valsubject4_6', 'entity': 'timm877', 'root_dir': 'C:\\Users\\Tim de Boer\\Documents\\VU\\Master_Artificial_Intelligence\\9_BCI_MasterProject\\BCI_Code\\unicorn_MI_BCI', 'run_id': 's1kjw5ns', 'sweep_param_path': 'C:\\Users\\Tim de Boer\\Documents\\VU\\Master_Artificial_Intelligence\\9_BCI_MasterProject\\BCI_Code\\unicorn_MI_BCI\\wandb\\sweep-7esp2m17\\config-s1kjw5ns.yaml', 'sweep_id': '7esp2m17'}
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'scripts\\3_TL.py', 'program': 'C:\\Users\\Tim de Boer\\Documents\\VU\\Master_Artificial_Intelligence\\9_BCI_MasterProject\\BCI_Code\\unicorn_MI_BCI\\scripts\\3_TL.py'}
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_init.py:_log_setup():428] Logging user logs to C:\Users\Tim de Boer\Documents\VU\Master_Artificial_Intelligence\9_BCI_MasterProject\BCI_Code\unicorn_MI_BCI\wandb\run-20220508_033944-s1kjw5ns\logs\debug.log
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_init.py:_log_setup():429] Logging internal logs to C:\Users\Tim de Boer\Documents\VU\Master_Artificial_Intelligence\9_BCI_MasterProject\BCI_Code\unicorn_MI_BCI\wandb\run-20220508_033944-s1kjw5ns\logs\debug-internal.log
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_init.py:init():462] calling init triggers
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_init.py:init():465] wandb.init called with sweep_config: {'D': 4, 'activation_type': 'elu', 'batch_size': 256, 'dropout': 0.25, 'epochs': 30, 'filter_sizing': 8, 'learning_rate': 0.005, 'mean_pool': 8, 'network': 'EEGNET', 'receptive_field': 64, 'seed': 42, 'val_subjects': ['X04', 'X06']}
config: {}
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [wandb_init.py:init():515] starting backend
2022-05-08 03:39:44,209 INFO    Thread-349:8888 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-05-08 03:39:44,225 INFO    Thread-349:8888 [backend.py:ensure_launched():217] starting backend process...
2022-05-08 03:39:44,290 INFO    Thread-349:8888 [backend.py:ensure_launched():222] started backend process with pid: 13924
2022-05-08 03:39:44,290 INFO    Thread-349:8888 [wandb_init.py:init():525] backend started and connected
2022-05-08 03:39:44,305 INFO    Thread-349:8888 [wandb_init.py:init():596] updated telemetry
2022-05-08 03:39:44,339 INFO    Thread-349:8888 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-05-08 03:39:46,616 INFO    Thread-349:8888 [wandb_run.py:_on_init():1924] communicating current version
2022-05-08 03:39:46,712 INFO    Thread-349:8888 [wandb_run.py:_on_init():1928] got version response 
2022-05-08 03:39:46,712 INFO    Thread-349:8888 [wandb_init.py:init():662] starting run threads in backend
2022-05-08 03:39:51,712 INFO    Thread-349:8888 [wandb_run.py:_config_callback():1136] config_cb None None {'D': 4, 'activation_type': 'elu', 'batch_size': 256, 'dropout': 0.25, 'epochs': 30, 'filter_sizing': 8, 'learning_rate': 0.005, 'mean_pool': 8, 'network': 'EEGNET', 'receptive_field': 64, 'seed': 42, 'val_subjects': ['X04', 'X06']}
2022-05-08 03:39:51,729 INFO    Thread-349:8888 [wandb_run.py:_console_start():1898] atexit reg
2022-05-08 03:39:51,731 INFO    Thread-349:8888 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.WRAP
2022-05-08 03:39:51,731 INFO    Thread-349:8888 [wandb_run.py:_redirect():1808] Wrapping output streams.
2022-05-08 03:39:51,731 INFO    Thread-349:8888 [wandb_run.py:_redirect():1832] Redirects installed.
2022-05-08 03:39:51,731 INFO    Thread-349:8888 [wandb_init.py:init():688] run started, returning control to user process
2022-05-08 03:39:53,865 INFO    Thread-349:8888 [wandb_watch.py:watch():47] Watching
2022-05-08 03:42:05,196 ERROR   Thread-7  :8888 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000020D48F3CF10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020D48F3CF10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\wandb\sdk\internal\internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Tim de Boer\anaconda3\envs\UnicornBCI\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020D48F3CF10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-05-08 03:47:26,512 INFO    Thread-349:8888 [wandb_run.py:_finish():1685] finishing run timm877/realsweep2-EEGNET-fullrun835Hz_valsubject4_6/s1kjw5ns
2022-05-08 03:47:26,513 INFO    Thread-349:8888 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2022-05-08 03:47:26,513 INFO    Thread-349:8888 [wandb_run.py:_restore():1839] restore
2022-05-08 03:47:27,457 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1000
  total_bytes: 1000
}

2022-05-08 03:47:27,780 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1000
  total_bytes: 1000
}

2022-05-08 03:47:28,764 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1000
  total_bytes: 9421
}

2022-05-08 03:47:28,880 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1000
  total_bytes: 32380
}

2022-05-08 03:47:28,999 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1000
  total_bytes: 32380
}

2022-05-08 03:47:29,115 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32380
  total_bytes: 32380
}

2022-05-08 03:47:29,234 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32380
  total_bytes: 32380
}

2022-05-08 03:47:29,338 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32380
  total_bytes: 32380
}

2022-05-08 03:47:29,456 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32380
  total_bytes: 32380
}

2022-05-08 03:47:29,578 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32380
  total_bytes: 32380
}

2022-05-08 03:47:29,682 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32380
  total_bytes: 32380
}

2022-05-08 03:47:30,387 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32380
  total_bytes: 32380
}

2022-05-08 03:47:30,880 INFO    Thread-349:8888 [wandb_run.py:_on_finish():1996] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32380
  total_bytes: 32380
}
local_info {
}

2022-05-08 03:47:32,476 INFO    Thread-349:8888 [wandb_run.py:_footer_history_summary_info():3104] rendering history
2022-05-08 03:47:32,476 INFO    Thread-349:8888 [wandb_run.py:_footer_history_summary_info():3136] rendering summary
2022-05-08 03:47:32,500 INFO    Thread-349:8888 [wandb_run.py:_footer_sync_info():3060] logging synced files
